language: node_js

node_js:
    - "6"

sudo: false

script: npm run-script coverage

after_success:
    - npm install https://github.com/alekitto/ocular.js.git
    - $(npm bin)/ocular coverage/clover.xml
